// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9TxhXWQK6c9h0g-VuZdqAHx8iUY9vNSE',
    appId: '1:213089433559:web:ca2264d76179bfb311fd92',
    messagingSenderId: '213089433559',
    projectId: 'myfirestore-5f49d',
    authDomain: 'myfirestore-5f49d.firebaseapp.com',
    storageBucket: 'myfirestore-5f49d.appspot.com',
    measurementId: 'G-X6VFVMQL2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYppEqn0FCjayQ-IuuQnzHUWVQyFPLLGQ',
    appId: '1:213089433559:android:4f6abe157aad625211fd92',
    messagingSenderId: '213089433559',
    projectId: 'myfirestore-5f49d',
    storageBucket: 'myfirestore-5f49d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrL93jPlW5qaxy5jqGZFZwNym3Zjd5-GU',
    appId: '1:213089433559:ios:f41e0e8cbef7064e11fd92',
    messagingSenderId: '213089433559',
    projectId: 'myfirestore-5f49d',
    storageBucket: 'myfirestore-5f49d.appspot.com',
    iosClientId: '213089433559-7f9gsp41r46onm4sphdf78hc7bpjnegl.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrL93jPlW5qaxy5jqGZFZwNym3Zjd5-GU',
    appId: '1:213089433559:ios:f41e0e8cbef7064e11fd92',
    messagingSenderId: '213089433559',
    projectId: 'myfirestore-5f49d',
    storageBucket: 'myfirestore-5f49d.appspot.com',
    iosClientId: '213089433559-7f9gsp41r46onm4sphdf78hc7bpjnegl.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramclone',
  );
}
